portfolio/urls.py
from django.contrib import admin
from django.urls import path

from charity.views import LandingPage, AddDonation, Login, Register, LogoutView, DonationConfirmation, Profile, \
    EditProfile

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', LandingPage.as_view(), name='landing_page'),
    path('form/', AddDonation.as_view(), name='add_donation'),
    path('login/', Login.as_view(), name='login'),
    path('register/', Register.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('thankyou/', DonationConfirmation.as_view(), name='thank_you'),
    path('profile/', Profile.as_view(), name='profile'),
    path('edit/', EditProfile.as_view(), name='edit'),

]

charity/models.py
from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db import models

# Create your models here.
TYPES = ((1, 'Fundacja'),
         (2, 'Organizacja pozarządowa'),
         (3, 'Zbiórka lokalna'))


class Category(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name

class Institution(models.Model):
    name = models.CharField(max_length=64)
    description = models.TextField()
    type = models.IntegerField(choices=TYPES, default=1)
    categories = models.ManyToManyField(Category)

    def __str__(self):
        return self.name

class Donation(models.Model):
    quantity = models.IntegerField()
    categories = models.ManyToManyField(Category)
    institution = models.ForeignKey(Institution, on_delete=models.CASCADE)
    address = models.CharField(max_length=64)
    phone_regex = RegexValidator(regex=r'^\+?\d{9,15}$',
                                 message="Numer telefonu musi być w formacie: '+999999999'. Max. 15 cyfr")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True)
    city = models.CharField(max_length=64)
    zip_code_regex = RegexValidator(regex=r'^\d{2}-\d{3}$',
                                    message="Kod pocztowy musi być w formacie: '00-000'.")
    zip_code = models.CharField(validators=[zip_code_regex], max_length=6, blank=True)
    pick_up_date = models.DateField(auto_now_add=False)
    pick_up_time = models.TimeField(null=True)
    pick_up_comment = models.TextField()
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    is_taken = models.BooleanField(null=True, default=False)

charity/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.views import View
from charity.models import Donation, Institution, Category


class LandingPage(View):
    def get(self, request):
        ctx = {}
        donations = Donation.objects.all()
        foundations = Institution.objects.filter(type=1)
        organizations = Institution.objects.filter(type=2)
        local = Institution.objects.filter(type=3)

        institutions_qt = Institution.objects.all().count()
        donated_qt = 0
        for donation in donations:
            donated_qt += donation.quantity

        ctx['donated_qt'] = donated_qt
        ctx['institutions_qt'] = institutions_qt
        ctx['foundations'] = foundations
        ctx['organizations'] = organizations
        ctx['local'] = local

        return render(request, 'index.html', ctx)


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('landing_page')


class AddDonation(View):
    def get(self, request):
        if request.user.is_authenticated:
            ctx = {}
            categories = Category.objects.all()
            institutions = Institution.objects.all()
            ctx['categories'] = categories
            ctx['institutions'] = institutions
            return render(request, 'form.html', ctx)
        else:
            return redirect('login')

    def post(self, request):
        categories = request.POST.getlist('categories')
        bags = request.POST.get('bags')
        address = request.POST.get('address')
        city = request.POST.get('city')
        postcode = request.POST.get('postcode')
        phone = request.POST.get('phone')
        pick_up_date = request.POST.get('data')
        time = request.POST.get('time')
        comment = request.POST.get('more_info')
        institution = request.POST.get('organization')
        user = request.user

        new_donation = Donation.objects.create(quantity=bags,
                                               address=address,
                                               phone_number=phone,
                                               city=city,
                                               zip_code=postcode,
                                               pick_up_date=pick_up_date,
                                               pick_up_time=time,
                                               pick_up_comment=comment,
                                               institution_id=institution,
                                               user_id=user.id)
        new_donation.categories.set(categories)

        return redirect('thank_you')


class DonationConfirmation(View):
    def get(self, request):
        return render(request, 'form-confirmation.html')


class Login(View):
    def get(self, request):
        return render(request, 'login.html')

    def post(self, request):
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(username=email, password=password)

        if user is not None:
            login(request, user)
            return redirect('landing_page')
        else:
            return redirect('register')


class Register(View):
    def get(self, request):
        return render(request, 'register.html')

    def post(self, request):
        name = request.POST.get('name')
        surname = request.POST.get('surname')
        email = request.POST.get('email')
        password = request.POST.get('password')
        password2 = request.POST.get('password2')

        if password == password2:
            if not User.objects.get(email=email):
                User.objects.create_user(first_name=name,
                                         last_name=surname,
                                         email=email,
                                         password=password,
                                         username=email)
            else:
                messages.error(request, 'User with this email already exists.')
                return redirect('register')

        return redirect('login')


class Profile(View):
    def get(self, request):
        ctx = {}
        donations = Donation.objects.filter(user_id=request.user.id).order_by('is_taken', '-pick_up_date')

        ctx['user'] = request.user
        ctx['donations'] = donations

        return render(request, 'profile.html', ctx)

    def post(self, request):
        if request.POST.get('archive'):
            donation = Donation.objects.get(id=request.POST.get('archive'))
            donation.is_taken = True
            donation.save()
            return redirect('profile')


class EditProfile(View):
    def get(self, request):
        ctx = {}
        ctx['user'] = request.user

        return render(request, 'profile-edit.html', ctx)

    def post(self, request):
        user = User.objects.get(id=request.user.id)

        if user.check_password(request.POST['old-password']):
            user.first_name = request.POST.get('name')
            user.last_name = request.POST.get('surname')
            user.email = request.POST.get('email')
            user.username = request.POST.get('email')

            if request.POST.get('password') and request.POST.get('password') == request.POST.get('password2'):
                user.set_password(request.POST.get('password'))
                update_session_auth_hash(request, user)
        else:
            messages.error(request, 'Hasło nieprawidłowe. Podaj hasło, żeby zapisać zmiany.')
            return redirect('edit')

        user.save()
        messages.success(request, 'Zmiany zostały zapisane.')
        return redirect('profile')

charity/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    <title>Oddam w dobre ręce | {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href={% static "css/style.css" %}/>
</head>
<body>
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li class="{{ message.tags }}">{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
{% block header_open %}
{% endblock %}

<nav class="container container--70">
    <ul class="nav--actions">
        {% if user.is_authenticated %}
            <li class="logged-user">
                Witaj {{ user.first_name }}
                <ul class="dropdown">
                    <li><a href="{% url 'profile' %}">Profil</a></li>
                    <li><a href="{% url 'edit' %}">Ustawienia</a></li>
                    {% if user.is_superuser %}
                        <li><a href="{% url 'admin' %}">Panel administracyjny</a></li>
                    {% endif %}
                    <li><a href="{% url 'logout' %}">Wyloguj</a></li>
                </ul>
            </li>
        {% else %}
            <li><a href="{% url 'login' %}" class="btn btn--small btn--without-border">Zaloguj</a></li>
            <li><a href="{% url 'register' %}" class="btn btn--small btn--highlighted">Załóż konto</a></li>
        {% endif %}
    </ul>


    <ul>
        <li><a href="{% url 'landing_page' %}" class="btn btn--without-border active">Start</a></li>
        <li><a href="{% url 'landing_page' %}#steps" class="btn btn--without-border">O co chodzi?</a></li>
        <li><a href="{% url 'landing_page' %}#about-us" class="btn btn--without-border">O nas</a></li>
        <li><a href="{% url 'landing_page' %}#help" class="btn btn--without-border">Fundacje i organizacje</a></li>
        {% if user.is_authenticated %}
            <li><a href="{% url 'add_donation' %}#donate"
                   class="btn btn--without-border">Przekaż dary</a></li>{% endif %}
        <li><a href="#contact" class="btn btn--without-border">Kontakt</a></li>
    </ul>
</nav>

{% block header_close %}
{% endblock %}

{% block content %}
{% endblock %}

<footer>
    <div id="contact" class="contact">
        <h2>Skontaktuj się z nami</h2>
        <h3>Formularz kontaktowy</h3>
        <form class="form--contact">
            <div class="form-group form-group--50"><input type="text" name="name" placeholder="Imię"/></div>
            <div class="form-group form-group--50"><input type="text" name="surname" placeholder="Nazwisko"/></div>

            <div class="form-group"><textarea name="message" placeholder="Wiadomość" rows="1"></textarea></div>

            <button class="btn" type="submit">Wyślij</button>
        </form>
    </div>
    <div class="bottom-line">
        <span class="bottom-line--copy">Copyright &copy; 2019</span>
        <div class="bottom-line--icons">
            <a href="#" class="btn btn--small"><img src="{% static "images/icon-facebook.svg" %}"/></a>
            <a href="#" class="btn btn--small"><img src="{% static "images/icon-instagram.svg" %}"/></a>
        </div>
    </div>
</footer>

</body>
</html>

charity/templates/form-confirmation.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Przekaż dary
{% endblock %}
{% block header_open %}
    <header class="header--form-page">
{% endblock %}
</header>
{% block content %}
        <div class="slogan container container--90">
            <h2>
                Dziękujemy za przesłanie formularza<br>
                Na maila prześlemy wszelkie
                informacje o odbiorze.
            </h2>
        </div>
    <script src="{% static "js/app.js" %}"></script>
{% endblock %}

charity/templates/form.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Przekaż dary
{% endblock %}
{% block header_open %}
    <header class="header--form-page">
{% endblock %}

{% block header_close %}
    <div class="slogan container container--90">
        <div class="slogan--item">
            <h1>
                Oddaj rzeczy, których już nie chcesz<br/>
                <span class="uppercase">potrzebującym</span>
            </h1>

            <div class="slogan--steps">
                <div class="slogan--steps-title">Wystarczą 4 proste kroki:</div>
                <ul class="slogan--steps-boxes">
                    <li>
                        <div><em>1</em><span>Wybierz rzeczy</span></div>
                    </li>
                    <li>
                        <div><em>2</em><span>Spakuj je w worki</span></div>
                    </li>
                    <li>
                        <div><em>3</em><span>Wybierz fundację</span></div>
                    </li>
                    <li>
                        <div><em>4</em><span>Zamów kuriera</span></div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    </header>
{% endblock %}

{% block content %}

    <section id="donate" class="form--steps">
        <div class="form--steps-instructions">
            <div class="form--steps-container">
                <h3>Ważne!</h3>
                <p data-step="1" class="active">
                    Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
                    wiedzieć komu najlepiej je przekazać.
                </p>
                <p data-step="2">
                    Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
                    wiedzieć komu najlepiej je przekazać.
                </p>
                <p data-step="3">
                    Wybierz jedną, do
                    której trafi Twoja przesyłka.
                </p>
                <p data-step="4">Podaj adres oraz termin odbioru rzeczy.</p>
            </div>
        </div>

        <div class="form--steps-container">
            <div class="form--steps-counter">Krok <span>1</span>/5</div>

            <form action="." method="post">
                {% csrf_token %}
                <!-- STEP 1: class .active is switching steps -->
                <div data-step="1" class="active">
                    <h3>Zaznacz co chcesz oddać:</h3>

                    {% for category in categories %}
                    <div class="form-group form-group--checkbox">
                        <label>
                            <input
                                    type="checkbox"
                                    name="categories"
                                    value="{{ category.id }}"
                            />
                            <span class="checkbox"></span>
                            <span class="description"
                            >{{ category.name }}</span
                            >
                        </label>
                    </div>
                    {% endfor %}


                    <div class="form-group form-group--buttons">
                        <button type="button" class="btn next-step">Dalej</button>
                    </div>
                </div>

                <!-- STEP 2 -->
                <div data-step="2">
                    <h3>Podaj liczbę 60l worków, w które spakowałeś/aś rzeczy:</h3>

                    <div class="form-group form-group--inline">
                        <label>
                            Liczba 60l worków:
                            <input type="number" name="bags" step="1" min="1"/>
                        </label>
                    </div>

                    <div class="form-group form-group--buttons">
                        <button type="button" class="btn prev-step">Wstecz</button>
                        <button type="button" class="btn next-step">Dalej</button>
                    </div>
                </div>


                <!-- STEP 4 -->
                <div data-step="3">
                    <h3>Wybierz organizacje, której chcesz pomóc:</h3>

                    {% for institution in institutions %}
                        <div class="form-group form-group--checkbox"
                             data-category="
                                     {% for category in institution.categories.all %}{{ category.id }} {% endfor %}">
                        <label>
                            <input type="radio" name="organization" value="{{ institution.id }}"/>
                            <span class="checkbox radio"></span>
                            <span class="description">
                  <div class="title">{{ institution.name }}</div>
                  <div class="subtitle">
                    Cel i misja: {{ institution.description }}
                  </div>
                </span>
                        </label>
                    </div>
                    {% endfor %}


                    <div class="form-group form-group--buttons">
                        <button type="button" class="btn prev-step">Wstecz</button>
                        <button type="button" class="btn next-step">Dalej</button>
                    </div>
                </div>

                <!-- STEP 5 -->
                <div data-step="4">
                    <h3>Podaj adres oraz termin odbioru rzecz przez kuriera:</h3>

                    <div class="form-section form-section--columns">
                        <div class="form-section--column">
                            <h4>Adres odbioru</h4>
                            <div class="form-group form-group--inline">
                                <label> Ulica <input type="text" name="address"/> </label>
                            </div>

                            <div class="form-group form-group--inline">
                                <label> Miasto <input type="text" name="city"/> </label>
                            </div>

                            <div class="form-group form-group--inline">
                                <label>
                                    Kod pocztowy <input type="text" name="postcode"/>
                                </label>
                            </div>

                            <div class="form-group form-group--inline">
                                <label>
                                    Numer telefonu <input type="phone" name="phone"/>
                                </label>
                            </div>
                        </div>

                        <div class="form-section--column">
                            <h4>Termin odbioru</h4>
                            <div class="form-group form-group--inline">
                                <label> Data <input type="date" name="data"/> </label>
                            </div>

                            <div class="form-group form-group--inline">
                                <label> Godzina <input type="time" name="time"/> </label>
                            </div>

                            <div class="form-group form-group--inline">
                                <label>
                                    Uwagi dla kuriera
                                    <textarea name="more_info" rows="5"></textarea>
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group form-group--buttons">
                        <button type="button" class="btn prev-step">Wstecz</button>
                        <button type="button" class="btn next-step">Dalej</button>
                    </div>
                </div>

                <!-- STEP 6 -->
                <div data-step="5">
                    <h3>Podsumowanie Twojej darowizny</h3>

                    <div class="summary">
                        <div class="form-section">
                            <h4>Oddajesz:</h4>
                            <ul>
                                <li>
                                    <span class="icon icon-bag"></span>
                                    <span class="summary--text"
                                    >4 worki ubrań w dobrym stanie dla dzieci</span
                                    >
                                </li>

                                <li>
                                    <span class="icon icon-hand"></span>
                                    <span class="summary--text"
                                    >Dla fundacji "Mam marzenie" w Warszawie</span
                                    >
                                </li>
                            </ul>
                        </div>

                        <div class="form-section form-section--columns">
                            <div class="form-section--column">
                                <h4>Adres odbioru:</h4>
                                <ul id="address">
                                    <li>Prosta 51</li>
                                    <li>Warszawa</li>
                                    <li>99-098</li>
                                    <li>123 456 789</li>
                                </ul>
                            </div>

                            <div class="form-section--column">
                                <h4>Termin odbioru:</h4>
                                <ul id="term">
                                    <li>13/12/2018</li>
                                    <li>15:40</li>
                                    <li>Brak uwag</li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    <div class="form-group form-group--buttons">
                        <button type="button" class="btn prev-step">Wstecz</button>
                        <button type="submit" class="btn">Potwierdzam</button>
                    </div>
                </div>
            </form>

        </div>
    </section>
    <script src="{% static "js/app.js" %}"></script>
{% endblock %}

charity/templates/login.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Logowanie
{% endblock %}
{% block header_open %}
    <header class="">
{% endblock %}

{% block header_close %}
    </header>
{% endblock %}


{% block content %}


    <section class="login-page">
        <h2>Zaloguj się</h2>
        <form method="post" action="/login/">
            {% csrf_token %}
            <div class="form-group">
                <input type="email" name="email" placeholder="Email"/>
            </div>
            <div class="form-group">
                <input type="password" name="password" placeholder="Hasło"/>
                <a href="#" class="btn btn--small btn--without-border reset-password">Przypomnij hasło</a>
            </div>

            <div class="form-group form-group--buttons">
                <a href="{% url 'register' %}" class="btn btn--without-border">Załóż konto</a>
                <button class="btn" type="submit">Zaloguj się</button>
            </div>
        </form>
    </section>

{% endblock %}

charity/templates/profile-edit.html
{% extends 'base.html' %}
{% block title %}
    Rejestracja
{% endblock %}
{% block header_open %}
    <header class="">
{% endblock %}

{% block header_close %}
    </header>
{% endblock %}

{% block content %}
    <section class="login-page">
        <h2>Edytuj dane</h2>
        <form action="." method="post">
            {% csrf_token %}
            <div class="form-group">
                Imię: <input type="text" name="name" value="{{ user.first_name }}"/>
            </div>
            <div class="form-group">
                Nazwisko: <input type="text" name="surname" value="{{ user.last_name }}"/>
            </div>
            <div class="form-group">
                Email: <input type="email" name="email" value="{{ user.email }}"/>
            </div>
            <div class="form-group">
                Hasło: <input type="password" name="old-password" placeholder="Obecne hasło"/>
                <br>Podaj hasło, żeby zapisać zmiany.
            </div>
            <div class="form-group">
                Nowe hasło: <input type="password" name="password" placeholder="Nowe hasło"/>
            </div>
            <div class="form-group">
                Nowe hasło: <input type="password" name="password2" placeholder="Powtórz hasło"/>
            </div>

            <div class="form-group form-group--buttons">
                <button class="btn" type="submit" name="edit">Zapisz</button>
            </div>
        </form>
    </section>
{% endblock %}

charity/templates/profile.html
{% extends 'base.html' %}
{% block title %}
    Twój profil
{% endblock %}
{% block header_open %}
    <header class="">
{% endblock %}

{% block header_close %}
    </header>
{% endblock %}

{% block content %}
    <h2>
        Email: {{ user.email }}<br>
        Imię i nazwisko: {{ user.get_full_name }}
    </h2>
    <section class="stats">
        <div class="container container--90">
            <div class="stats--item">
                {% for donation in donations %}

                    <h3>{{ donation.quantity }} worków</h3>
                    <p> Dla organizacji <strong>{{ donation.institution }}</strong></p>
                    Dary w kategoriach: {{ donation.category_set.all }}
                    {% for category in donation.categories.all %}
                        {{ category }}{% if not forloop.last %},{% endif %}
                    {% endfor %}<br>
                    Data odebrania: {{ donation.pick_up_date }}<br>
                    {% if donation.is_taken %}<span style="color: red">ZARCHIWIZOWANO</span>
                    {% else %}
                        <form action="." method="post">
                            {% csrf_token %}
                            <button class="btn btn-archive" name="archive" type="submit" value="{{ donation.id }}">Zarchiwizuj
                            </button>
                        </form>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}

charity/templates/register.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Rejestracja
{% endblock %}
{% block header_open %}
    <header class="">
{% endblock %}

{% block header_close %}
    </header>
{% endblock %}

{% block content %}
    <section class="login-page">
        <h2>Załóż konto</h2>
        <form action="/register/" method="post">
            {% csrf_token %}
            <div class="form-group">
                <input type="text" name="name" placeholder="Imię"/>
            </div>
            <div class="form-group">
                <input type="text" name="surname" placeholder="Nazwisko"/>
            </div>
            <div class="form-group">
                <input type="email" name="email" placeholder="Email"/>
            </div>
            <div class="form-group">
                <input type="password" name="password" placeholder="Hasło"/>
            </div>
            <div class="form-group">
                <input type="password" name="password2" placeholder="Powtórz hasło"/>
            </div>

            <div class="form-group form-group--buttons">
                <a href="{% url 'login' %}" class="btn btn--without-border">Zaloguj się</a>
                <button class="btn" type="submit">Załóż konto</button>
            </div>
        </form>
    </section>


{% endblock %}